<a href="https://colab.research.google.com/github/Kaavyagarg/Data_Analysis/blob/main/numpy%26pandas_20_12_2022.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
l1=[1,2,34,45]
print(l1)
na1 = np.array(l1)
na1

[1, 2, 34, 45]


array([ 1,  2, 34, 45])

In [ ]:
array_3 = np.array([1,2,3,4.4], dtype='U')
print(array_3)

['1' '2' '3' '4.4']


In [ ]:
arr = np.array([0,1,2])
arr * 2

array([0, 2, 4])

In [ ]:
arr1 = np.array([1,3,5,7,9])
print(type(arr1))
l1 = list(arr1)
print(type(l1))
list_1
print(np.multiply(list_1,2))

print(list(np.multiply(list_1,2)))

<class 'numpy.ndarray'>
<class 'list'>
[0 2 4]
[0, 2, 4]


In [ ]:
float_array = np.array([[10, 34, 35], [125, 851, 0]], dtype='f')
print ("Float numbers array created from list", float_array)

Float numbers array created from list [[ 10.  34.  35.]
 [125. 851.   0.]]


In [ ]:
arrange_array= np.arange(0,5,1) #arranging array by giving end value
print("arranging array from 0 to 4:\n",arrange_array)

arranging array from 0 to 4:
 [0 1 2 3 4]


In [ ]:
arrange_array2=  np.arange(6, dtype='f')
print("arranging array with given end point:\n",arrange_array2)

arranging array with given end point:
 [0. 1. 2. 3. 4. 5.]


In [ ]:
arrange_array2=  np.array(range(6), dtype='U')
print("arranging array with given end point:\n",arrange_array2)

arranging array with given end point:
 ['0' '1' '2' '3' '4' '5']


In [ ]:
array_with_ones= np.ones(5, dtype='i')
print("arranging array with all ones given rows and columns:\n",array_with_ones)
array_with_zeros = np.zeros(4, dtype = 'i')
print ("\n Array of defined size initialized with zeros:\n", array_with_zeros)
array_with_zeros = np.zeros((3,2))
print ("\n Array of defined size initialized with zeros:\n", array_with_zeros)


arranging array with all ones given rows and columns:
 [1 1 1 1 1]

 Array of defined size initialized with zeros:
 [0 0 0 0]

 Array of defined size initialized with zeros:
 [[0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
Random_array = np.random.random((3,3))
print ("\n Random numbers array:\n", Random_array)

print(np.random.randint(10,25, size = (5,6)))


 Random numbers array:
 [[0.39180617 0.14640376 0.75341603]
 [0.24744749 0.03680817 0.96924782]
 [0.36003226 0.17076459 0.21067666]]
[[12 13 10 12 19 12]
 [23 14 22 19 11 23]
 [14 10 22 12 19 10]
 [10 18 13 23 13 23]
 [22 24 17 17 12 11]]


In [ ]:
new_array = np.linspace(10, 20, 5)
print ("\nA sequential array with 8 values between"
                                        "20 and 50:\n", new_array)
print(np.linspace(1,10,4))


A sequential array with 8 values between20 and 50:
 [10.  12.5 15.  17.5 20. ]
[ 1.  4.  7. 10.]


In [ ]:
array_1 = np.array([[1,2,3,4],[5,4,6,7],[2,3,4,6]])
print(array_1)
# Syntax.arrayname.shape
array_1.shape
  # shape (the size of each dimension)

[[1 2 3 4]
 [5 4 6 7]
 [2 3 4 6]]


(3, 4)

In [ ]:
orig_arr_1 = np.array([10, 32, 36, 34, 4, 55]) ## 1D array
reshaped_arr_1 = orig_arr_1.reshape(3, 2)
print ("\nOriginal array:\n", orig_arr_1)
print ("\n Reshaped array:\n", reshaped_arr_1)
print ("\n Dimension of original array:\n", orig_arr_1.ndim)
print ("\n dimension of Reshaped array:\n", reshaped_arr_1.ndim)


Original array:
 [10 32 36 34  4 55]

 Reshaped array:
 [[10 32]
 [36 34]
 [ 4 55]]

 Dimension of original array:
 1

 dimension of Reshaped array:
 2


In [ ]:
orig_arr_2 = np.array([[10, 32, 36], [34, 4, 55], [4,77,67]])   ## 2D Array

reshaped_arr_2 = orig_arr_2.reshape(9)
print ("\nOriginal array:\n", orig_arr_2)
print ("\n Reshaped array:\n", reshaped_arr_2)
print ("\n dimension of original array:\n", orig_arr_2.ndim)
print ("\n dimension of Reshaped array:\n", reshaped_arr_2.ndim)


Original array:
 [[10 32 36]
 [34  4 55]
 [ 4 77 67]]

 Reshaped array:
 [10 32 36 34  4 55  4 77 67]

 dimension of original array:
 2

 dimension of Reshaped array:
 1


In [ ]:
# Flatten array
arr = np.array([[[1, 2, 3], [4, 5, 6]]])
flarr = arr.flatten()

print ("\nOriginal array:\n", arr)
print ("Fattened array:\n", flarr)


Original array:
 [[[1 2 3]
  [4 5 6]]]
Fattened array:
 [1 2 3 4 5 6]


In [ ]:
array_multiD = np.array([
                [100, 14, 76, 54],
                [125, 81, 0, -24],
                [566, 159, 175, 20],
                [38, -47, 84, 22.0]],dtype = int)

print("Shape of the array is: ", array_multiD.ndim, array_multiD.shape)

## 81 is in the 1st row and 1st column
print("Accessing 1st row: ", array_multiD[0])
print("Accessing 1st column: ", array_multiD[:, 1])  ## : indicates all the rows
print("Accessing (1st row, 1st column): ", array_multiD[2,1])  # calling 159

Shape of the array is:  2 (4, 4)
Accessing 1st row:  [100  14  76  54]
Accessing 1st column:  [ 14  81 159 -47]
Accessing (1st row, 1st column):  159


In [ ]:
array_example = np.array([[10, 32, 36, 34],
                [125, 851, 0, -24],
                [56, 19, 75, 20],
                [3, -7, 4, 2.0]])

# Slicing array
## Access first 2 rows
sliced_array = array_example[0:2, :]   #:2 returns the 0,1 indexed row
print(sliced_array)

[[ 10.  32.  36.  34.]
 [125. 851.   0. -24.]]


In [ ]:
#Items of an array can be modified in any place of an array like below
array = np.ones((4, 5))
print("original array\n",array)

## Replace a value at 2nd row, 2nd column to 10
array[2, 2] = 10
print("modified array\n",array)

original array
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
modified array
 [[ 1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.]
 [ 1.  1. 10.  1.  1.]
 [ 1.  1.  1.  1.  1.]]


In [ ]:
sample_arr = np.array([[5, 215, 69],
                       [44, 74, 21],
                       [30, 12, 94]])

# maximum element of array
print ("Largest element of array :", sample_arr.max())
print ("Row-wise maximum elements:",
                    sample_arr.max(axis = 1))

Largest element of array : 215
Row-wise maximum elements: [215  74  94]


In [ ]:
sample_arr = np.array([[1, 4, 2],
                       [3, 4, 6],
                       [0, -1, 5]])

# sorted array
print ("Array elements in sorted order:\n",np.sort(sample_arr, axis = None))

Array elements in sorted order:
 [-1  0  1  2  3  4  4  5  6]


In [ ]:
converted_arr = arr.astype('bool')
print(arr)
print(converted_arr.dtype)
print(converted_arr)


[[[1 2 3]
  [4 5 6]]]
bool
[[[ True  True  True]
  [ True  True  True]]]


In [ ]:
arr_concat1 = np.array([2, 2, 6, 8])
arr_concat2 = np.array([1, 3, 5, 7])
final_arr = np.concatenate((arr_concat1, arr_concat2))
print("1d concatenated array : \n",final_arr)


1d concatenated array : 
 [2 2 6 8 1 3 5 7]


In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

print(np.concatenate((a, b.T), axis=1))
print(np.concatenate((a, b), axis=None))

print(b.T)
print(a)

[[1 2 5]
 [3 4 6]]
[1 2 3 4 5 6]
[[5]
 [6]]
[[1 2]
 [3 4]]


In [ ]:
import numpy as np
arr_all = np.array([123, 345, 29, 24, 80, 61, 79, 84])

arr_odd_index = np.where(arr_all%2 == 1)

print(arr_odd_index)

(array([0, 1, 2, 5, 6]),)


In [ ]:
array_to_split = np.array([6, 1, 7, 9, 10, 4, 43, 28, 54])

split_array = np.array_split(array_to_split , 3)

print(split_array)

print(split_array[0])
print(split_array[1])
print(split_array[2])

[array([6, 1, 7]), array([ 9, 10,  4]), array([43, 28, 54])]
[6 1 7]
[ 9 10  4]
[43 28 54]


In [ ]:
array = np.arange(36.0).reshape(6, 6)

hsplit_arr = np.hsplit(array, 3)

print("Array before splitting : \n", array)
print("\n Array after horizontal split : \n \n",hsplit_arr)

print(type(np.hsplit(array, 3)))
print(len(np.hsplit(array, 3)))

print(type(hsplit_arr))
hsplit_arr[0]

Array before splitting : 
 [[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]
 [24. 25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34. 35.]]

 Array after horizontal split : 
 
 [array([[ 0.,  1.],
       [ 6.,  7.],
       [12., 13.],
       [18., 19.],
       [24., 25.],
       [30., 31.]]), array([[ 2.,  3.],
       [ 8.,  9.],
       [14., 15.],
       [20., 21.],
       [26., 27.],
       [32., 33.]]), array([[ 4.,  5.],
       [10., 11.],
       [16., 17.],
       [22., 23.],
       [28., 29.],
       [34., 35.]])]
<class 'list'>
3
<class 'list'>


array([[ 0.,  1.],
       [ 6.,  7.],
       [12., 13.],
       [18., 19.],
       [24., 25.],
       [30., 31.]])

In [ ]:
arr_1 = np.array([[7, 3],
                 [1, 4]])

arr_2 = np.array([[1, 9],
                  [4, 0]])
column = [5, 6]
print("Vertical stacking:\n", np.vstack((arr_1, arr_2)))
print("\nColumn stacking:\n", np.column_stack((arr_1, column)))

Vertical stacking:
 [[7 3]
 [1 4]
 [1 9]
 [4 0]]

Column stacking:
 [[7 3 5]
 [1 4 6]]


In [ ]:
import numpy as np
array = np.array([5, 6, 7])
array_2 = [2.0, 2.0, 2.0]
print("output on arrays multiplication :",array * array_2)

array_2 - np.ones((1,3))*2


output on arrays multiplication : [10. 12. 14.]


array([[0., 0., 0.]])

In [ ]:
a = np.arange(3)
b = np.arange(2)[:, np.newaxis] #it is equal to b.reshape(2,1)
c = a+b
print(c)
print(c.shape)

[[0 1 2]
 [1 2 3]]
(2, 3)


Intro to pandas_21.12.2022

In [ ]:
import pandas as pd

# Create empty series and check its data type
s1 = pd.Series()
# Check its type and print series
type(s1)

<ipython-input-5-34b9730812db>:4: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  s1 = pd.Series()


pandas.core.series.Series

In [ ]:
import pandas as pd
import numpy as np

array = ['r', 'e', 'l', 'e', 'v','e','l']
# Convert the given array to pandas series and print the series
series = pd.Series(array)
print(series)

0    r
1    e
2    l
3    e
4    v
5    e
6    l
dtype: object


In [ ]:
### Creating a series from array with index
data = np.array(['r', 'e', 'l', 5, 'v','e','l'])

# Giving an index [1, 10, 20, 30, 40, 50, 60] to series
series = pd.Series(data, index = [101, 10, 20, 30, 40, 50, 60])
print(series)

101    r
10     e
20     l
30     5
40     v
50     e
60     l
dtype: object


In [ ]:
dict_to_convert = {'Monday' : 0,
                   'Tuesday' : 2,
                    'Wednesday' : 4}

# create series from dictionary
series = pd.Series(dict_to_convert)

print(series)

Monday       0
Tuesday      2
Wednesday    4
dtype: int64


In [ ]:
df = pd.DataFrame()
print(df)
type(df)

Empty DataFrame
Columns: []
Index: []


pandas.core.frame.DataFrame

In [ ]:
# Calling DataFrame constructor on list
# Syntax: pandas.DataFrame(data=None, index=None, columns=None)
sentence_token = ['Relevel', 'is', 'the', 'best',
            'platform', 'to', 'learn','python']
df = pd.DataFrame(sentence_token, index = ['o', 'i', 'ii', 'iii', 'iv', 'v', 'vi', 'vii'], columns = ['string11'])
print(df)
print(type(df))
df['string11']['i']

print(df['string11']['o'])
print(type(df))
print(type(df['string11']))

     string11
o     Relevel
i          is
ii        the
iii      best
iv   platform
v          to
vi      learn
vii    python
<class 'pandas.core.frame.DataFrame'>
Relevel
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>


In [ ]:
import pandas as pd
state_data = {'State':['MP', 'UP', 'DL', None], 'Code': [10,15,19,24]}
pd.DataFrame({'State':'MP', 'capital': 'bhopal'}, index = [1, 2, 3])

# Create DataFrame with index value ['City 1', 'City 2', 'City 3', 'City 4']
df_2 = pd.DataFrame(data = state_data, index=['City 1', 'City 2', 'City 3', 'City 4'])

# Print the output.
print(df_2)

       State  Code
City 1    MP    10
City 2    UP    15
City 3    DL    19
City 4  None    24


In [ ]:
# Create a numpy array
nparray = np.array(
    [['Amar', 'Akbar', 'Ram', 'Ravi'],
     [29, 25, 33, 24],
     ['PR', 'Marketing', 'IT', 'Finance']])

# Create a dictionary of nparray
dictionary_of_nparray = {
    'Name': nparray[0],
    'Age': nparray[1],
    'Department': nparray[2]}

# Create the DataFrame
df1 = pd.DataFrame(nparray)
print(df1)
print(df1.shape)

df2 = pd.DataFrame(dictionary_of_nparray)
print(df2)
print(df2.shape)

      0          1    2        3
0  Amar      Akbar  Ram     Ravi
1    29         25   33       24
2    PR  Marketing   IT  Finance
(3, 4)
    Name Age Department
0   Amar  29         PR
1  Akbar  25  Marketing
2    Ram  33         IT
3   Ravi  24    Finance
(4, 3)


In [ ]:
# Define a dictionary containing data
data = {'Name':['Hari', 'Ronak', 'Harleen', 'Parveen'],
        'Gender':["M", "M", "F", "F"],
        'Address':['Delhi', 'Kanpur', 'Allahabad', 'Kannauj'],
        'Age':[24, 26, 21, 30]}

# Convert the dictionary into DataFrame
df = pd.DataFrame(data)

# print name column
print(df.columns.tolist())
print(list(df.columns))

['Name', 'Gender', 'Address', 'Age']
['Name', 'Gender', 'Address', 'Age']


In [ ]:
# Define a dictionary containing data
data = {'Name':['Hari', 'Ronak', 'Harleen', 'Parveen'],
        'Gender':["M", "M", "F", "F"],
        'Age':[24, 26, 21, 30]}

# Convert the dictionary into DataFrame
df = pd.DataFrame(data)
print(df)
# Declare a list that is to be converted into a column
address = ['Mumbai', 'Vellore', 'Pune', 'Agra']

## Add address column from address variable mentioned above
df['Address'] = address
print(df)

      Name Gender  Age
0     Hari      M   24
1    Ronak      M   26
2  Harleen      F   21
3  Parveen      F   30
      Name Gender  Age  Address
0     Hari      M   24   Mumbai
1    Ronak      M   26  Vellore
2  Harleen      F   21     Pune
3  Parveen      F   30     Agra


In [ ]:
import pandas as pd

dict_for_df  = {'Fruits':['Mango', 'Banana', 'Watermelon', 'Grapes'],
                    'Number of Kgs sold':[5, 10, 8, 4],
                    'Cost per Kg':[500, 80, 100, 170],
                   'Selling price per kg': [700, 120, 150, 200]}

# Creating the DataFrame
df = pd.DataFrame(dict_for_df)

# Print the dataframe
df

# create a new column based on the following formula
# Number of Kgs sold * (Selling price per kg - Cost per Kg)
df['Profit'] = df['Number of Kgs sold'] * (df['Selling price per kg'] - df['Cost per Kg'])

# Print the DataFrame after
# addition of new column
df

df1 = df.assign(profit = lambda x: x['Number of Kgs sold'] * (x['Selling price per kg'] - x['Cost per Kg']))
df1

Fruits  Number of Kgs sold  Cost per Kg  Selling price per kg  Profit  \
0       Mango                   5          500                   700    1000   
1      Banana                  10           80                   120     400   
2  Watermelon                   8          100                   150     400   
3      Grapes                   4          170                   200     120   

   profit  
0    1000  
1     400  
2     400  
3     120

In [ ]:
### Deleting Column"""

# Define a dictionary containing data
data = {'Name':['Hari', 'Ronak', 'Harleen', 'Parveen'],
        'Gender':["M", "M", "F", "F"],
        'Address':['Delhi', 'Kanpur', 'Allahabad', 'Kannauj'],
        'Age':[24, 26, 21, 30]}

# Convert the dictionary into DataFrame
df = pd.DataFrame(data)

# dropping Gender columns
fd1 = df.drop(['Age', 'Gender'], axis = 1)
print(fd1)

      Name    Address
0     Hari      Delhi
1    Ronak     Kanpur
2  Harleen  Allahabad
3  Parveen    Kannauj


In [ ]:
### Deleting Rows
# Define a dictionary containing data
data = {'Name':['Hari', 'Ronak', 'Harleen', 'Parveen'],
        'Gender':["M", "M", "F", "F"],
        'Address':['Delhi', 'Kanpur', 'Allahabad', 'Kannauj'],
        'Age':[24, 26, 21, 30]}

# Convert the dictionary into DataFrame
df = pd.DataFrame(data)

# dropping passed values ["Avery Bradley", "John Holland"]

df.drop([0,1]) #by default axis=0
df.drop(range(0,2))


Name Gender    Address  Age
2  Harleen      F  Allahabad   21
3  Parveen      F    Kannauj   30

In [ ]:
# Convert the dictionary into DataFrame
df = pd.DataFrame(data)
data1 = pd.DataFrame({'Name': ['Prime', 'JOHN'], 'Gender': ['M','M'], 'Address': ['Pune', 'jkl'], 'Age':[25, 45]})

data2 = pd.DataFrame({'Name': ['yee', 'jane'], 'Gender': ['M','F'], 'Address': ['Pune', 'jkl'], 'Age':[12, 8]}, index=[6,7])

df.append([data1, data2])
#by default the index starts from 0

Name Gender    Address  Age
0     Hari      M      Delhi   24
1    Ronak      M     Kanpur   26
2  Harleen      F  Allahabad   21
3  Parveen      F    Kannauj   30
0    Prime      M       Pune   25
1     JOHN      M        jkl   45
6      yee      M       Pune   12
7     jane      F        jkl    8

In [ ]:
df1 = pd.DataFrame({'ID': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], 'Name': ['aa', 'bb', 'cc', 'dd', 'ee', 'ff', 'gg', 'hh', 'ii', 'jj'],
       'salary': [1407, 1416, 1272, 1803, 1725, 1280, 1651, 1374, 1628, 1512], 'bonus': [158, 192, 113, 105, 117, 151, 103, 139, 160, 108]})
df2 = pd.DataFrame({'ID': [11, 12, 13, 14, 15, 16, 17, 18, 19, 20], 'Name': ['aa1', 'bb1', 'cc1', 'dd1', 'ee1', 'ff1', 'gg1', 'hh1', 'ii1', 'jj1'],
       'salary': [1607, 1646, 1262, 1063, 1765, 1260, 1661, 1764, 1668, 1562], 'bonus': [128, 122, 123, 205, 127, 121, 123, 129, 102, 182]})

pd.concat([df1, df2], ignore_index = True)

ID Name  salary  bonus
0    1   aa    1407    158
1    2   bb    1416    192
2    3   cc    1272    113
3    4   dd    1803    105
4    5   ee    1725    117
5    6   ff    1280    151
6    7   gg    1651    103
7    8   hh    1374    139
8    9   ii    1628    160
9   10   jj    1512    108
10  11  aa1    1607    128
11  12  bb1    1646    122
12  13  cc1    1262    123
13  14  dd1    1063    205
14  15  ee1    1765    127
15  16  ff1    1260    121
16  17  gg1    1661    123
17  18  hh1    1764    129
18  19  ii1    1668    102
19  20  jj1    1562    182